spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=joshuapop1782004@gmail.com
spring.mail.password=tsjp hjpw etyu sbgx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.imap.host=imap.gmail.com
app.mail.imap.port=993

